<?php

use Illuminate\Database\Seeder;

class AddonsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('addons')->insert([
        'add_en' => 'Tshirt',
        'add_ms' => 'Baju',
        'add_zh' => '衣服',
        'addprice' => 12.00,
        'desc_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'desc_ms' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'desc_zh' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'type' => 'S, M, L',
        'races_id' => 2,
      ]);

      DB::table('addons')->insert([
        'add_en' => 'Tote Bag',
        'add_ms' => 'Tote Beg',
        'add_zh' => '包包',
        'addprice' => 22.00,
        'desc_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'desc_ms' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'desc_zh' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'type' => 'Red, Blue, Yellow',
        'races_id' => 8,
      ]);
    }
}
