<?php

use Illuminate\Database\Seeder;

class RacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*DB::table('races')->insert([
            'title' => '21Day Challenge Sep 2018',
            'date_from' => '2018-08-17 00:00 am',
            'date_to' => '2018-08-21 00:00 am',
            'dead_from' => '2018-08-09 00:00 am',
            'dead_to' => '2018-08-16 00:00:00 am',
            'price' => 122.00,
            'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
            'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
            'header' => 'WEB BANNER  1900x1000_1534488318.jpg',
      ]);*/

      DB::table('races')->insert([
        'title' => 'Bangi Wonderland Non-Competitive Ride 130km',
        'date_from' => '2018-08-23 00:00 am',
        'date_to' => '2018-08-25 00:00 am',
        'dead_from' => '2018-08-14 00:00 am',
        'dead_to' => '2018-08-22 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Charity Red Socks Run Banner.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Family Run Ride Walk',
        'date_from' => '2018-06-28 00:00 am',
        'date_to' => '2018-06-30 00:00 am',
        'dead_from' => '2018-06-20 00:00 am',
        'dead_to' => '2018-06-27 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Charity Family Fun Ride & Walk Poster.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'We Love Klang Run 2018',
        'date_from' => '2018-09-23 00:00 am',
        'date_to' => '2018-09-25 00:00 am',
        'dead_from' => '2018-09-15 00:00 am',
        'dead_to' => '2018-09-22 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'WLKR 2018 Howei Thumbnail_0.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'PPGS IPOH 5KM',
        'date_from' => '2018-11-07 00:00 am',
        'date_to' => '2018-11-09 00:00 am',
        'dead_from' => '2018-10-31 00:00 am',
        'dead_to' => '2018-11-06 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'hos-thumb.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Autism Charity Run 2018',
        'date_from' => '2018-11-15 00:00 am',
        'date_to' => '2018-11-17 00:00 am',
        'dead_from' => '2018-11-12 00:00 am',
        'dead_to' => '2018-11-14 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Autism Chairty Ruhn Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Charity Run',
        'date_from' => '2018-12-04 00:00 am',
        'date_to' => '2018-12-06 00:00 am',
        'dead_from' => '2018-11-26 00:00 am',
        'dead_to' => '2018-12-03 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'PROJEK KASIH Charity Run 4k x 4k This-page-001.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Lemang @Bentong fun run',
        'date_from' => '2018-01-23 00:00 am',
        'date_to' => '2018-01-25 00:00 am',
        'dead_from' => '2018-01-16 00:00 am',
        'dead_to' => '2018-01-22 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'lemang_thumb.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Peace road charity run penang',
        'date_from' => '2018-02-02 00:00 am',
        'date_to' => '2018-02-04 00:00 am',
        'dead_from' => '2018-01-25 00:00 am',
        'dead_to' => '2018-02-01 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Peace Road Charity Run Penang 2018 Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Star Track Charity',
        'date_from' => '2018-02-15 00:00 am',
        'date_to' => '2018-02-17 00:00 am',
        'dead_from' => '2018-02-07 00:00 am',
        'dead_to' => '2018-02-14 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'StartrackCRFRThumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Ultimate trails of penang',
        'date_from' => '2018-04-12 00:00 am',
        'date_to' => '2018-04-14 00:00 am',
        'dead_from' => '2018-04-06 00:00 am',
        'dead_to' => '2018-04-13 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Ultimate Trails Of Penang 2018 Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'Bangi Wonderland 130km',
        'date_from' => '2018-06-28 00:00 am',
        'date_to' => '2018-06-30 00:00 am',
        'dead_from' => '2018-06-12 00:00 am',
        'dead_to' => '2018-06-29 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'Bangi Wonderland Non-Competitive 130km Thumbnail_0.jpg',
      ]);

      DB::table('races')->insert([
        'title' => 'The Last Tanjung Aru',
        'date_from' => '2018-07-23 00:00 am',
        'date_to' => '2018-07-25 00:00 am',
        'dead_from' => '2018-07-15 00:00 am',
        'dead_to' => '2018-07-22 00:00:00 am',
        'price' => 50.00,
        'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'header' => 'The Last Tanjung Aru Beach Run 2018 Thumbnail.jpg',
      ]);
    }
}
