<?php

use Illuminate\Database\Seeder;

class RacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('races')->insert([
        'title_en' => 'Double Ninth Festival Virtual Run',
        'title_ms' => 'Larian Virtual Festival Sembilan Kembar',
        'title_zh' => '重阳节线上跑',
        'date_from' => '2018-09-23',
        'date_to' => '2018-09-25',
        'dead_from' => '2018-09-14',
        'dead_to' => '2018-09-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km',
        'price' => 0,
        'about_en' => "<p>The Double Ninth Festival is observed on the ninth day of the ninth month in the Chinese Calendar and a traditional Chinese holiday.</p><p>Some countries also dub this holiday as 'Senior Citizens' Day', where they take this opportunity to care for and appreciate the elderly. Originally celebrated as a day to drive away danger, as time passed, it has now evolved into a day of celebrations.</p><p>People typically take this day to hike and appreciate chrysanthemum, key features of this beautiful holiday.</p><p>Let us preserve this beautiful culture - grab your family and friends and celebrate Double Ninth Festival unlike any other!</p>",
        'about_ms' => "<p>Festival Sembilan Kembar diamati pada hari kesembilan dari bulan kesembilan dalam Kalender Tiongkok dan hari libur tradisional Tiongkok.</p><p>Beberapa negara juga menjuluki liburan ini sebagai 'Hari Warga Senior', di mana mereka mengambil kesempatan ini untuk merawat dan menghargai para lansia. Awalnya dirayakan sebagai hari untuk mengusir bahaya, seiring berlalunya waktu, kini telah berevolusi menjadi hari perayaan.</p><p>Orang biasanya mengambil hari ini untuk mendaki dan menghargai bunga krisan, fitur utama dari liburan yang indah ini.</p><p>Mari kita lestarikan budaya yang indah ini - ambil keluarga dan teman-teman anda dan rayakan Festival Sembilan Kembar yang tidak seperti yang lain!</p>",
        'about_zh' => "<p>每年农历的九月九号，重阳节，是非常重要的一个节日。但，这天要怎么过呢？</p><p>有人会把重阳节又称作「敬老节」，因为这天，我们可以把握机会，和长辈相聚，陪陪爷爷奶奶或阿公阿嬷。虽然重阳节的由来，本来是为了趋吉避凶，不过这几年，它已经变成一个快乐庆祝的节日了！</p><p>有些人会选在这天，去登山或是赏菊。但你可以过得更不一样！今年，就带着你的亲朋好友，用这场线上跑，度过一个不一样的节日吧！</p>",
        'awards_en' => "",
        'awards_ms' => "",
        'awards_zh' => "",
        'medals_en' => "<p>The e-badge features all things traditionally essential to celebrate Double Ninth Festival - chrysanthemums and mountains, where people would climb mountains and admire chrysanthemums.</p><p>Since it's also known as 'Senior Citizens Day', in the e-badge you can see a few senior citizens going towards the mountain in the foreground. This e-badge is meant to include all the special characteristics of the festival into one image, to remind you of this wonderful holiday that still exists!</p>",
        'medals_ms' => "<p>E-lencana memiliki semua hal yang secara tradisional penting untuk merayakan Festival Sembilan Kembar - krisan dan gunung, di mana orang akan mendaki gunung dan mengagumi bunga krisan.</p><p>Karena itu juga dikenal sebagai 'Hari Warga Senior', di e-lencana anda dapat melihat beberapa warga senior pergi ke arah gunung di latar depan. E-lencana ini dimaksudkan untuk memasukkan semua karakteristik khusus festival ke dalam satu gambar, untuk mengingatkan anda tentang liburan indah ini yang masih ada!</p>",
        'medals_zh' => "<p>你看，所有重阳节的特色，都在这面电子奖牌上了！</p><p>美丽的菊花和一座座的山脉，你看，还有一群长辈们，正在沿着山路往上爬呢！看到这面电子奖牌，就让我们不禁想起，这个欢乐又美丽的节日了呢！</p>",
        'header' => 'double-ninth-festival.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Great Barrier Reef Marathon Virtual Run',
        'title_ms' => 'Larian Virtual Great Barrier Reef Marathon',
        'title_zh' => '大堡礁马拉松线上跑',
        'date_from' => '2018-08-23',
        'date_to' => '2018-08-25',
        'dead_from' => '2018-08-18',
        'dead_to' => '2018-08-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '5km,10km,21km,42km',
        'price' => 50.00,
        'about_en' => "<p>So we've brought you to races that come from beautiful places like Danang in Vietnam, but this time, we have partnered with the Great Barrier Reef Marathon Festival to bring you to the Great Barrier Reef.<p><p>They work closely with charities to raise awareness on the plight of the Great Barrier Reef as well as protect Whale Sharks and Manta Rays.</p><p>The reef is home to the worlds biggest abundance of marine life and is one of the Seven Wonders of the World. If we do not conserve and protect, it might not be there for our future generations to appreciate. </p><p>It's now time to take greater action, to protect this wonderful place we call our Home. </p>",
        'about_ms' => '<p>Jadi kami telah membawa anda ke perlombaan yang datang dari tempat-tempat indah seperti Danang di Vietnam, tetapi kali ini, kami telah bermitra dengan Great Barrier Reef Marathon Festival untuk membawa anda ke Karang Penghalang Besar.</p><p>Mereka bekerja erat dengan badan amal untuk meningkatkan kesadaran tentang penderitaan Karang Penghalang Besar serta melindungi Hiu Paus dan Ikan Pari Manta.</p><p>Terumbu karang adalah rumah bagi kelimpahan terbesar kehidupan laut dan merupakan salah satu dari Tujuh Keajaiban Dunia. Jika kita tidak melestarikan dan melindunginya, mungkin tidak akan ada bagi generasi mendatang kita untuk menghargainya.</p><p>Sekarang saatnya untuk mengambil tindakan yang lebih besar, untuk melindungi tempat indah yang kita sebut Rumah kita ini.</p>',
        'about_zh' => '<p>好的赛事，常有美景相伴，像是之前的越南岘港线上跑，就有着满满的异国风情。而这一次，我们请来大堡礁马拉松节，就是要给你全新的体验！</p><p>大堡礁马拉松节，与慈善团体密切合作，致力于大堡礁，鲸鲨和鬼蝠魟的保育。你知道吗？大堡礁是世界七大奇景之一，更是最大的海洋生物孕育之地。如果不好好保护它，这样的美景将会消失在我们这一代。那可不行！</p><p>是时候，用行动，捍卫我们的美丽的海洋家园了！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>The medal features the "Heart Reef" - one of the most famous sights of the Great Barrier Reef. It is called the "Heart Reef" because the natural corals formed in the shape of a heart. </p><p>The front of the medal is filled with a blue ocean-colored tinted gel paint to replicate the actual iconic site with a Whale Shark in the middle and a manta ray on the top left hand corner - 2 of the main species in need of protection.</p><p>When you turn the medal, you\'ll see the name of the run as well as that of the official Great Barrier Reef Marathon. We hope that this medal will remind you of the importance of the need to protect, as well as the fragility of the corals.</p>',
        'medals_ms' => 'Medali ini menampilkan "Heart Reef" - salah satu pemandangan paling terkenal dari Karang Penghalang Besar. Ini disebut "Heart Reef" karena karang alami terbentuk dalam bentuk hati.</p><p>Bagian depan medali diisi dengan cat gel berwarna berwarna biru laut untuk mereplikasi situs ikonik dengan Hiu Paus di tengah - salah satu spesies utama yang membutuhkan perlindungan.</p><p>Ketika anda membalik medali, anda akan melihat nama larian dan juga nama resmi Great Barrier Reef Marathon. Kami berharap medali ini akan mengingatkan anda tentang pentingnya kebutuhan untuk melindungi, serta kerapuhan karang.</p>',
        'medals_zh' => '<p>奖牌的设计，以大堡礁的著名景点「心型礁」为主轴，你也许在照片上看过，那浑然天成的心型珊瑚礁，真的太美了！</p><p>而奖牌的正面，则完美再现了心型礁的美丽色泽 - 和大海一样纯净的蓝色奖牌中央的鲸鲨，是亟需保育的物种之一，也象征着海洋保育的重要性。</p><p>把奖牌翻过来，你会看见赛事名称和大堡礁马拉松的字样，看见它，希望你能想起蔚蓝的海洋，和值得我们细细呵护的美丽礁石。</p>',
        'header' => 'great-barrier-reef.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Halloween Virtual Run 2018',
        'title_ms' => 'Larian Virtual Halloween',
        'title_zh' => '万圣节线上跑',
        'date_from' => '2018-06-28',
        'date_to' => '2018-06-30',
        'dead_from' => '2018-06-20',
        'dead_to' => '2018-06-27',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km,42km',
        'price' => 50.00,
        'about_en' => "<p>This fun and spooky festival is bacccckk! This year, we are bringing the most imaginative, spookiest and memorable run of the year to you!</p><p>Imagine yourself running in your smashing halloween costume, trick-or-treating around your neighbourhood. You are dressed in one of your favourite movie characters, dashing out the door with an empty bag, ready to collect your sweet treats along the way! 'Too much sweet treats for me!', said no one ever.</p><p>So, what are you waiting for? Call out your friends and family to join this race with you today!</p><p>Happy running and trick-or-treating!</p>",
        'about_ms' => '<p>Festival paling menyenangkan dan menakutkan kembali lagiiii!</p><p>Tahun ini, kami membawa anda mengalami salah satu perjalanan paling imajinatif, berhantu, dan berkesan sepanjang tahun.</p><p>Bayangkan diri anda sedang berlari dalam kostum halloween anda, trick-or-treat di sekitar lingkungan anda! Anda mengenakan salah satu karakter film favorit anda, siap untuk berlari keluar pintu dengan tas kosong untuk mengumpulkan makanan manis di sepanjang jalan! "Terlalu banyak camilan manis untukku!", Tak seorang pun pernah kata.</p><p>Jadi, apa yang kamu tunggu? Panggil teman dan keluarga anda untuk bergabung dengan balapan ini bersama anda hari ini!</p><p>Selamat berlari dan trick-or-treat!</p>',
        'about_zh' => '<p>最有趣和可以搞怪的的节日回来啰！</p><p>今年我们将带您体验一年中最富有想像力和发挥搞怪的时候到了，让我们一起参加最恐怖难忘的线上赛事吧！想像一下穿着准备好的万圣节服装参加赛事沿路拍照记录下来，上传在脸书和Instagram的上面让你在社交媒体上引爆朋友的话题性，让朋友也一起加入你的行列这不是一件很有趣的经验嘛！</p><p>你还在等什么？立刻邀请你的朋友和家人参加这场搞怪的赛事吧！</p><p>快乐的跑步和捣蛋！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>The medal is the perfect representation of this year\'s halloween run! </p><p>The pumpkin in the middle depicts the spooky halloween spirit. When we think about Halloween season, what\'s the first thing you think of? Black cats? Superstition? Then this medal is perfect for you! </p><p>Black cats have long been associated with halloween - which is the main focus for this medal, to make it extra \'halloweeny\'! </p><p>Sign up today so you don\'t miss this memorable run with us!</p>',
        'medals_ms' => '<p>Medali ini adalah representasi sempurna untuk larian halloween tahun ini!</p><p>Labu di tengah menggambarkan roh halloween yang menyeramkan. Ketika kita berpikir tentang musim Halloween, kita sering berpikir tentang binatang seperti kucing! Kucing hitam telah lama dikaitkan dengan halloween; mereka seperti prajurit, selalu siap untuk menaklukkan dan bertarung! Dalam hal kebugaran, kita semua bisa seperti mereka juga - dengan mendaftar di perlombaan ini, anda siap untuk menaklukkan dan memenangkan perlombaan ini!</p><p>Daftar hari ini agar anda tidak melewatkan perjalanan yang mengesankan ini bersama kami! :) </p>',
        'medals_zh' => '<p>今年奖牌设计是万圣节最经典的元素”南瓜“应该没有比南瓜能够取代万圣节经典元素之一了吧！ ！ ！</p><p>奖牌中间的南瓜描绘了搞怪的万圣节精神。当我们想到万圣节的季节时，你首先想到的是什么？黑猫？南瓜？如果是这样那么这枚奖牌对你来说完全符合你的想像！</p><p>马上报名赛事，这样您就不会错过这次难忘的跑步经验吧！</p>',
        'header' => 'halloween.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Happy Lungs Virtual Run',
        'title_ms' => 'Larian Virtual Paru-paru Bahagia ',
        'title_zh' => '快乐不「肺」力线上跑',
        'date_from' => '2018-09-23',
        'date_to' => '2018-09-25',
        'dead_from' => '2018-09-15',
        'dead_to' => '2018-09-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km',
        'price' => 0.00,
        'about_en' => "<p>Did you know that our lungs are one of the most vital organs in our body? That’s because without it, we won’t be able to breathe! Additionally, our lungs play a very important role in our ability to speak!</p><p>Thus, it is very important that we take the necessary preventative measures to keep our lungs healthy! One of which is to stay away from smoking and to stay active by running! This is why we would like to invite you to our Happy Lungs Virtual Run 2018!</p><p>Join us in this race to keep your lungs healthy and happy! </p>",
        'about_ms' => '<p>Tahukah anda bahwa paru-paru kita adalah salah satu organ paling vital di tubuh kita? Itu karena tanpanya, kita tidak akan bisa bernapas! Selain itu, paru-paru kita memainkan peran yang sangat penting dalam kemampuan kita untuk berbicara!</p><p>Dengan demikian, sangat penting bahwa kita mengambil tindakan pencegahan yang diperlukan untuk menjaga kesehatan paru-paru kita! Salah satunya adalah untuk hindari merokok dan tetap aktif dengan berlari! Inilah mengapa kami ingin mengundang anda ke Larian Virtual Paru-paru Bahagia 2018 kami!</p><p>Bergabunglah bersama kami dalam lomba ini untuk membuata paru-paru anda sehat dan bahagia!</p>',
        'about_zh' => '<p>你知道吗？在我们的所有的器官之中，肺脏可是数一数二重要的！如果没有肺的话，我们就没办法呼吸了！还有还有，我们能够说话，也都要感谢它呢！</p><p>既然肺脏这么重要，那当然要好好保养它啦！怎么做呢？除了不要抽烟之外，没错，就是跑步！所以你还在什么，现在就加入快乐不「肺」力线上跑 2018吧！</p><p>加入我们，一起拥抱健康和快乐，不「肺」力！</p>',
        'awards_en' => '',
        'awards_ms' => '',
        'awards_zh' => '',
        'medals_en' => '<p>This e-badge features a pair of Happy and Healthy lungs to serve as a reminder of encouraging us to lead a healthy lifestyle and take good care of our lungs!</p><p>This pair of healthy lungs is also lifting up a finisher plaque to show that they will always be there playing an important role in our body functions. So, run with us in the Happy Lungs Virtual Run 2018 to keep your lungs in tip-top condition!</p>',
        'medals_ms' => '<p>E-lencana ini memiliki sepasang paru-paru yang Bahagia dan Sehat untuk berfungsi sebagai pengingat untuk mendorong kita untuk menjalani gaya hidup sehat dan merawat paru-paru dengan baik!</p><p>Sepasang paru-paru yang sehat ini juga mengangkat plakat penuntas untuk menunjukkan bahwa mereka akan selalu ada memainkan peran penting dalam fungsi tubuh kita. Jadi, jalankan bersama kami di Larian Virtual Paru-paru Bahagia 2018 untuk menjaga paru-paru anda dalam kondisi prima!</p>',
        'medals_zh' => '<p>这面电子奖牌上，有一对带着笑容的小肺脏，哈哈，它们这是在鼓励你，生活要健康一点，还有别忘了好好照顾它们！</p><p>你看，这对可爱的小肺脏，正努力把赛事完成的字样挂上去呢！这代表着无论何时，它们都会一直维持好身体的运作，成为你最坚强的后盾！唉唷，怎么这么窝心啦～看来要赶快加入快乐不「肺」力线上跑 2018，用最健康的状态，回馈我们的肺了，对吧～</p>',
        'header' => 'happy-lung.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Wild West Virtual Run',
        'title_ms' => 'Larian Virtual Wild West',
        'title_zh' => '西部世界线上跑',
        'date_from' => '2018-11-07',
        'date_to' => '2018-11-09',
        'dead_from' => '2018-10-31',
        'dead_to' => '2018-11-06',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>Ever wondered how life in the Old West was? Now you can with this run!</p><p>Transporting you back into time, it is now 1867 and we're in the period of the Old West. Cowboys, native Indians, outlaws and even gamblers run the town - the justice system is flawed and there is barely any order. Everyone is looking for an opportunity and they aren't afraid of a little mischief and adventure. </p><p>As Sheriff, the safety of the town is now your responsibility. Do you have what it takes to bring peace back into town? It's time to catch the outlaws and show them whose boss in this town.</p>",
        'about_ms' => '<p>Pernahkah bertanya-tanya bagaimana kehidupan di Old West itu? Sekarang anda bisa dengan larian ini!</p><p>Mengangkut anda kembali ke masa lalu, sekarang 1867 dan kita berada di periode Old West. Koboi, penduduk asli, penjahat dan bahkan penjudi menjalankan kota - sistem peradilan cacat dan hampir tidak ada perintah apa pun. Setiap orang mencari peluang dan mereka tidak takut dengan sedikit kenakalan dan petualangan.</p><p>Sebagai Sheriff, keamanan kota sekarang menjadi tanggung jawab anda. Apakah anda memiliki apa yang diperlukan untuk membawa perdamaian kembali ke kota? Sudah waktunya untuk menangkap penjahat dan tunjukkan pada mereka siapa bosnya di kota ini.</p>',
        'about_zh' => '<p>看过西部片吧？现在你将化身为主角！</p><p>穿越时空，现在是1867年年，你回到了美国的西部时代。牛仔，印地安人，盗匪和赌徒主宰了整个城镇，体制已然崩坏，秩序不再。人人都想出头，一旦机会来临，就算冒着生命危险，也在所不惜。</p><p>身为镇长的你，维护镇上的安全是你的责任。你有把握，让市镇重返和平吗？该你上场了，去吧，让那些不法之徒知道你的厉害！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>Relive adventures of the American Frontier with this medal - one that represents your hard work as Sheriff of the Old Town.</p><p>Inspired by the cowboys from the Old West, you can find cowboy hats resting on the frame that is quite symbolic from that time period. </p><p>The front of the medal features a cowboy riding on his horse in the desert whilst the back of the medal features an iconic phrase used widely by many cowboys from that era: "Yee-haw". </p>',
        'medals_ms' => '<p>Hidupkan kembali petualangan American Frontier dengan medali ini - salah satu yang mewakili kerja keras anda sebagai Old Town Sheriff.</p><p>Terinspirasi oleh koboi dari Old West, anda dapat menemukan topi koboi bertumpu pada bingkai yang cukup simbolis dari periode waktu itu.</p><p>Bagian depan medali menampilkan koboi menunggangi kudanya di padang pasir sementara bagian belakang medali menampilkan frasa ikonik yang digunakan secara luas oleh banyak koboi dari era itu "Yee-haw".</p>',
        'medals_zh' => '<p>戴上奖牌，迎向西部世界的精彩冒险！你就是英勇的镇长，这面奖牌，就是你努力的证明！</p><p>说到西部时代，绝对不能少了牛仔帽！奖牌的边框上，那一顶顶牛仔帽，是否正是你在西部片你看到的样子呢？</p><p>你看，奖牌的正面，是个骑着马，在沙漠中奔驰的帅气牛仔，翻到背面，则刻着最能代表牛仔精神的那句口号。你听，他正喊着呢，「噫哈！」</p>',
        'header' => 'wild-west.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Very Miss Rabbit Virtual Run',
        'title_ms' => 'Larian Virtual Very Miss Rabbit',
        'title_zh' => '好想兔线上跑',
        'date_from' => '2018-12-15',
        'date_to' => '2018-12-17',
        'dead_from' => '2018-12-12',
        'dead_to' => '2018-12-14',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>Stop wishing. Start doing; the exact reason why Very Miss Rabbit is coming to town this November!</p><p>Very Miss Rabbit has always been spoiled with good food - cakes, ice-cream and bubble tea are some of its favourite indulgence and it has never been able to stay away! Does that sound familiar to you? </p><p>It's time to put a stop to this - to make a healthy change!</p><p>In order to achieve this change, a goal is set - to maintain a healthy diet and start exercising!  If you have also set this goal and have yet to succeed, join this Very Miss Rabbit run and let's achieve our running goals together! </p>",
        'about_ms' => '<p>Berhenti berharap. Mulai lakukan; alasan yang tepat mengapa Very Miss Rabbit akan datang ke kota pada bulan September ini!</p><p>Very Miss Rabbit selalu dimanjakan dengan makanan yang enak - kue, es krim dan bubble tea adalah beberapa kesenangan favoritnya dan itu tidak pernah bisa menjauh! Apakah itu terdengar lazim bagi anda?</p><p>Saatnya untuk menghentikan ini - untuk membuat perubahan yang sehat!</p><p>Untuk mencapai perubahan ini, tujuan ditetapkan - untuk mempertahankan pola makan yang sehat dan mulai berolahraga! Jika anda juga telah menetapkan tujuan ini dan belum berhasil, bergabunglah dengan Very Miss Rabbit dan mari mencapai tujuan kami bersama!</p>',
        'about_zh' => '<p>别想了，做比较实在啦 - 让我们欢迎九月的重磅大明星，好想兔！</p><p>一直以来，好想兔就是个吃货，蛋糕在手，手摇要有，运动什么，我没听过。咦，你说听起来好像......说的就是你？</p><p>那么，是时候该做出改变了！连好想兔都跑起来了，你，还在等什么？</p><p>改变，就从饮食和运动习惯开始。什么，你说你想要运动，却一直没有动力？你的苦，我们懂！今天就加入好想兔线上跑的行列，让好想兔闪闪发亮的眼睛，陪着你向前冲吧，欸嘿！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>Take on the challenge and earn yourself this medal - illustrating your sporting success! Very Miss Rabbit holding on to the winner\'s trophy parallels your sporting journey, that as long as you keep on this path, you\'ll be celebrating your own wins -  a healthy life! </p><p>The happiness you emanate after achieving your fitness goals is translated through Very Miss Rabbit\'s expressions as it holds the trophy, celebrating! There is even a little crown on the top of the medal to remind yourself that as long as you try, you are a winner. Did we also mention that the medal is gold-colored? How fitting for a champion like yourself! </p><p>Be healthy. Be happy. Be like Very Miss Rabbit! </p>',
        'medals_ms' => '<p>Ambillah tantangan dan raihlah medali ini sendiri - mengilustrasikan kesuksesan olahraga anda! Very Miss Rabbit berpegang pada piala pemenang sejajar dengan perjalanan olahraga anda, bahwa selama anda tetap di jalur ini, anda akan merayakan kemenangan anda sendiri - sebuah hidup aehat!</p><p>Kebahagiaan yang anda pancarkan setelah mencapai tujuan kebugaran anda diterjemahkan melalui ekspresi Very Miss Rabbit saat memegang trofi, merayakan! Bahkan ada mahkota kecil di bagian atas medali untuk mengingatkan diri anda bahwa selama anda mencoba, anda adalah pemenang. Apakah kami juga menyebutkan bahwa medali dilapisi emas? Betapa pas untuk seorang juara seperti diri anda!</p><p>Jadilah sehat. Berbahagialah. Jadilah seperti Very Miss Rabbit!</p>',
        'medals_zh' => '<p>接下好想兔的挑战，赢得奖牌，纪念自己运动的辉煌成果吧！</p><p>准备好了吗，想兔粉们？好想兔将为你开启全新的运动旅程，有了想兔的陪伴，你将不再孤单。这条路，只要你坚持下去，你赢得的将不只是奖牌，而是属于自己的成功 - 也就是健康又充满光明的未来啊（远望</p><p>当你达成运动目标，这份喜悦，将有拿着奖杯的好想兔，和你一同欢呼庆祝！奖牌顶端还有一个小王冠，提醒着你，只要勇于尝试，你，就是赢家啦！</p><p>啊，忘了告诉你，奖牌是金色的，至于为什么呢......这就得问问你自己了，冠军！</p>',
        'header' => 'very-miss-rabbit.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Snow Fox Virtual Run',
        'title_ms' => 'Larian Virtual Rubah Salju',
        'title_zh' => '雪狐线上跑',
        'date_from' => '2019-03-12',
        'date_to' => '2019-03-06',
        'dead_from' => '2019-02-26',
        'dead_to' => '2019-03-03',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>To survive while living in one of the coldest parts of the world, tundra animals have expertly adapted their physiological makeup to battle the frigid Arctic conditions. </p><p>In this Artic Animals two-part series, we'll start by focusing on the Snow Fox.</p><p>Not only are they cute and one of the smallest animals in the Arctic kingdom, but they are also strong and intelligent beings. They are not your regular definition of a fox. </p><p>In our everyday life, we can emulate the snow foxes and learn valuable lessons from them – adapting to different situations can help us overcome any hardships. So, get out there and overcome your running challenges in the Snow Fox Virtual Run 2018!</p>",
        'about_ms' => '<p>Untuk bertahan hidup ketika tinggal di salah satu bagian terdingin di dunia, hewan tundra telah secara ahli menyesuaikan rias fisiologis mereka untuk melawan kondisi Arktik yang dingin.</p><p>Dalam seri dua bagian Hewan Kutub ini, kita akan mulai dengan berfokus pada Rubah Salju.</p><p>Tidak hanya mereka lucu dan salah satu hewan terkecil di kerajaan Arktik, tetapi mereka juga makhluk yang kuat dan cerdas. Mereka bukan definisi rubah biasa anda.</p><p>Dalam kehidupan kita sehari-hari, kita dapat meniru rubah salju dan belajar pelajaran berharga dari mereka - beradaptasi dengan situasi yang berbeda dapat membantu kita mengatasi setiap kesulitan. Jadi, keluarlah dan atasi tantangan larian anda di Larian Virtual Rubah Salju 2018!</p>',
        'about_zh' => '<p>你知道吗？为了在世界最冷的地方之一生存，住在冻原的动物们，发展出了独特的生理结构，以抵抗寒冷的极地环境。</p><p>「极地动物系列」将会有两场赛事，首先，这一次我们请出的是，雪狐！</p><p>超卡哇伊的雪狐，是极地地区最小的生物，但，可不只这样！它们还有强健的体力，和聪明的脑袋呢~可别把它和一般的狐狸混为一谈啦。</p><p>其实在生活中，我们可以从雪狐身上学到很多东西，并加以应用。比如说，跟雪狐一样，只要能适应各种状况，就能够克服一切困难！现在就加入雪狐线上跑2018，让雪狐陪着你，迎向你的跑步之旅！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>As their name indicates, snow foxes live in areas where there is snow! The snowflakes at the bottom of the medal, which are swingable, reflects this.</p><p>Two snow foxes can also be seen dancing happily on the front to show that although they live in harsh conditions, they are able to overcome the difficulties easily.</p><p>On the back, more snow foxes can be seen roaming around in their natural habitat of the arctic tundra.</p>',
        'medals_ms' => '<p>Seperti namanya, rubah salju hidup di daerah di mana ada salju! Kepingan salju di bagian bawah medali, yang dapat diayunkan, mencerminkan hal ini.!</p><p>Dua rubah salju juga dapat terlihat menari dengan gembira di depan untuk menunjukkan bahwa meskipun mereka hidup dalam kondisi yang keras, mereka dapat mengatasi kesulitan dengan mudah.</p><p>Di bagian belakang, lebih banyak rubah salju dapat terlihat berkeliaran di habitat alami tundra Arktik.</p>',
        'medals_zh' => '<p>「雪」狐「雪」狐，当然就是住在雪地里啦！所以我们在奖牌底部，设计了一片片的美丽雪花，而且你发现了吗，这些雪花还可以转动喔！</p><p>奖牌的正面，有两只雪狐，正快乐地跳着舞，你看，就算置身恶劣的环境，它们还是能克服万难，并乐在其中！</p><p>把奖牌翻到背面，你还可以看到更多可爱的雪狐，正在沿着它们的冻原栖息地，缓缓漫步呢。</p>',
        'header' => 'snow-fox.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Oven Break Virtual Run',
        'title_ms' => 'Larian Virtual Lolos Oven',
        'title_zh' => '拯救烤箱大作战线上跑',
        'date_from' => '2019-01-23',
        'date_to' => '2019-01-25',
        'dead_from' => '2019-01-16',
        'dead_to' => '2019-01-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km',
        'price' => 0.00,
        'about_en' => "<p>The festive season is nearly upon us and that can only mean one thing - baking season has begun! No festive season is complete without a gingerbread house! The sweet smell of cinnamon and vanilla fills every corner of the room... But wait, disaster has struck - all the cookies have escaped from the oven! The gingerbread men are running loose! It's up to us to catch them all and save the festive season! Will you be able to help us stop the oven break?!</p>",
        'about_ms' => '<p>Musim perayaan hampir tiba dan itu hanya berarti satu hal - musim pembuatan kue telah dimulai! Musim perayaan tidak lengkap tanpa rumah kue jahe! Bau manis kayu manis dan vanila memenuhi setiap sudut ruangan... Tapi tunggu, bencana telah melanda - semua kue telah lolos dari oven! Laki-laki jahe berlari lepas! Terserah kita untuk menangkap mereka semua dan menyelamatkan musim perayaan! Apakah anda dapat membantu kami menghentikan lolos oven ?!</p>',
        'about_zh' => '<p>12月的圣诞季就要到了，而这就代表了一件事——打开烤箱，快乐烘焙的时间就要来啦！圣诞季怎么能够没有姜饼屋呢，对吧？你好像已经可以闻到，香草和肉桂的香气，充斥在整个屋子里了…… 就在这个时候，等一下！咦，饼干们怎么全都从烤箱里跑出来了？ ！连姜饼人都开始到处乱跑！现在，得靠我们把失控的饼干们抓回来，才能让圣诞季顺利进行！你，愿意加入我们，一起迎向拯救烤箱大作战吗？</p>',
        'awards_en' => '',
        'awards_ms' => '',
        'awards_zh' => '',
        'medals_en' => '<p>As a token of our appreciation for rounding up all the cookies and saving the festive season, we present you with a beautifully decorated gingerbread house!</p><p>Complete with a gingerbread boy and gingerbread girl, this gingerbread house will surely be a great addition to our celebrations.</p><p>Let this e-badge be a reminder to us that a little bit of extra effort goes a long way - just like the extra effort it takes to make our gingerbread houses look better and better every year!</p>',
        'medals_ms' => '<p>Sebagai tanda penghargaan kami sedah mengumpulkan semua kue dan menyelamatkan musim perayaan, kami hadir dengan rumah roti jahe yang didekorasi dengan indah!</p><p>Lengkap dengan pria roti jahe dan gadis roti jahe, rumah roti jahe ini pastinya akan menjadi tambahan yang bagus untuk perayaan kami.</p><p>Biarlah e-lencana ini menjadi pengingat bagi kita bahwa sedikit usaha ekstra pergi jauh - seperti usaha ekstra yang diperlukan untuk membuat rumah kue jahe kita lebih baik setiap tahun!</p>',
        'medals_zh' => '<p>谢谢你帮忙找回了所有逃脱的饼干，拯救了今年的圣诞季！我们准备了一个超精致的姜饼屋，向你表达最～大的谢意！</p><p>你看，姜饼屋的旁边，还有一个姜饼男孩和姜饼女孩呢。他们也会陪着我们，一起庆祝这个欢乐的胜利时刻！</p><p>当你看到这面电子奖牌，希望你能想起，就算是小小的努力，只要多努力一点点，就能够得到很多！就像是今年，我们拯救了烤箱，这个小小的举动，就让姜饼屋变得更漂亮了！</p>',
        'header' => 'oven-break.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Thanksgiving Virtual Run',
        'title_ms' => 'Larian Virtual Pengucapan Syukur ',
        'title_zh' => '感恩节线上跑',
        'date_from' => '2019-02-02',
        'date_to' => '2019-02-04',
        'dead_from' => '2019-01-25',
        'dead_to' => '2019-02-01',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km',
        'price' => 0.00,
        'about_en' => "<p>Popular for its association to pumpkin pies and turkeys, Thanksgiving originally started out as a religious holiday to give thanks for a wonderful harvest season</p><p>Mainly celebrated in North America during the autumn months, it has since become a secular holiday - celebrating and giving thanks to those closest to us.</p><p>Why don't we join in on the celebrations and use this opportunity to look back on our running journeys! Let's give thanks to those who have supported us all throughout the ups and the downs!</p>",
        'about_ms' => '<p>Populer karena hubungannya dengan pai labu dan kalkun, Pengucapan Syukur menurut aslinya dimulai sebagai hari libur keagamaan untuk bersyukur untuk musim panen yang luar biasa.</p><p>Terutama dirayakan di Amerika Utara selama bulan-bulan musim gugur, sejak itu telah menjadi hari libur sekuler - merayakan dan mengucapkan terima kasih kepada orang-orang terdekat kita.</p><p>Mengapa tidak kita bergabung dalam perayaan dan menggunakan kesempatan ini untuk melihat kembali perjalanan kita yang sedang berjalan! Mari bersyukur kepada mereka yang telah mendukung kita selama pasang surut!</p>',
        'about_zh' => '<p>说到感恩节，大家最常联想到的就是火鸡和南瓜派了。而你知道吗，感恩节原本是一个宗教性的节日，以表达对于丰收祭的感谢。</p><p>你可能会问，那我为什么要过感恩节？别急嘛，现在感恩节已经不是宗教节日了，而是秋天的时候，向身边的人表达感谢的日子！</p><p>既然如此，就让我们借着这个机会回顾一下，一路跑来，受到了多少人的支持和鼓励呢？是时候，向那些跑步旅程上的恩人们，传达我们的感谢了！</p>',
        'awards_en' => '',
        'awards_ms' => '',
        'awards_zh' => '',
        'medals_en' => '<p>This e-badge is the winning entry in our latest Design Competition - thanks Ng Yi Kee for submitting a wonderful design!</p><p>Truly representative of all things Thanksgiving, this e-badge features autumnal elements to illustrate the season in which Thanksgiving is celebrated.</p><p>Two squirrels, inspired by the children\'s story "The Squirrels\' Thanksgiving", can be seen sharing a plate of pumpkin pie together. We, as runners, can imitate this behaviour by cultivating a community which motivates and encourages one another! Together, we inspire millions to run!</p>',
        'medals_ms' => '<p>E-lencana ini adalah entri pemenang dalam Kompetisi Desain terbaru kami - terima kasih Ng Yi Kee untuk mengirimkan desain yang luar biasa!</p><p>Benar-benar mewakili semua hal Pengucapan Syukur, e-lencana ini menampilkan elemen musim gugur untuk menggambarkan musim di mana Pengucapan Syukur dirayakan.</p><p>Dua tupai, terinspirasi oleh cerita anak-anak "The Squirrels\' Thanksgiving", dapat dilihat berbagi sepiring kue labu bersama-sama. Kami, sebagai pelari, dapat meniru perilaku ini dengan mengembangkan komunitas yang memotivasi dan mendorong satu sama lain! Bersama-sama, kami menginspirasi jutaan orang untuk berlari!</p>',
        'medals_zh' => '<p>哇，这面电子奖牌，是上一届设计大赛的得奖作品耶！谢谢奖牌的创作者Ng Yi Kee，设计得太棒了！</p><p>你看，所有感恩节的代表物，都在这面电子奖牌上了！整面奖牌充满了秋天的气息，看着它，就像是走进了秋天，好有感恩节的气氛啊～</p><p>奖牌上，有两只可爱的松鼠，正在一起分食着一盘南瓜派，这是取自于童话「松鼠的感恩节」。但其实，身为一名跑者，我们也可以向他们学习啊！和亲朋好友，组一个跑团，互相鼓励，向目标迈进！让我们一起，让上百万人跑起来！</p>',
        'header' => 'thanks-giving.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Samurai Virtual Run',
        'title_ms' => 'Larian Virtual Samurai',
        'title_zh' => '最强武士线上跑',
        'date_from' => '2019-02-15',
        'date_to' => '2019-02-17',
        'dead_from' => '2019-02-07',
        'dead_to' => '2019-02-14',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => '<p>Be inspired by the Japanese Warriors - Samurais, proficient in combat and life skills. </p><p>Most of them originated from humble beginnings, but over time, they became the dominant ruling class in Japan, with skills that overtook other classes of warriors. </p><p>They trained relentlessly and strongly believing in the principle of "being prepared", and this is something we can take away to our fitness journey. </p><p>Be humble like these Warriors but never be afraid to show and hone your skills - just like running, it takes practice but if we keep running, we will eventually get there.</p>',
        'about_ms' => '<p>Terinspirasilah oleh para Prajurit Jepang - Samurai, mahir dalam pertempuran dan keterampilan hidup.</p><p>Kebanyakan dari mereka berasal dari awal yang sederhana, tetapi seiring berjalannya waktu, mereka menjadi kelas penguasa yang dominan di Jepang, dengan keterampilan yang melampaui kelas-kelas prajurit lainnya.</p><p>Mereka berlatih tanpa henti dan kuat percaya pada prinsip "siap", dan ini adalah pelajaran yang dapat kita ambil dalam perjalanan kebugaran kita.</p><p>Bersikaplah rendah hati seperti para Prajurit ini tetapi jangan takut untuk menunjukkan dan mengasah kemampuan anda - seperti berlari, butuh latihan tetapi jika kita terus berlari, kita akhirnya akan sampai di sana.</p>',
        'about_zh' => '<p>你可能会说，对啦，我知道日本武士有着超强的决斗和生存能力，可这跟跑步有什么关系啊？</p><p>别急，先让我说完嘛。大部分的武士都出身低下，但最后却能够超越所有的士兵阶级，主宰整个日本。靠的是什么？没别的，就是在艰难的训练过程中，还能坚持着这个信念：随时让自己「准备好」。</p><p>太帅了吧！运动的这条路上，就是要有「随时准备好」的这种精神啊！</p><p>跟武士一样，我们可能出身平凡，但也不要害怕展现自己！只要坚持跑下去，总有一天，你也可以成为最强的武士，成为不凡！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>The front and back of the badge shows a Samurai in his fighting stance - typically seen during combat.</p><p>Behind him are 2 Katanas, also known as the \'single edge sword\'. It\'s said that a Samurai\'s sword represented his soul, and it symbolised their class, which made it an essential feature of this medal. </p><p>The back of the medal also features the iconic traits that define Japan, from Daruma dolls to Koi fishes!</p>',
        'medals_ms' => '<p>Bagian depan dan belakang lencana menunjukkan Samurai dalam posisi bertarung - biasanya terlihat selama pertempuran.</p><p>Di belakangnya ada 2 Katana, juga dikenal sebagai \'pedang besar\'. Dikatakan bahwa pedang Samurai mewakili jiwanya, dan itu melambangkan kelas mereka, yang membuatnya menjadi fitur penting dari medali ini.</p><p>Bagian belakang medali juga menampilkan ciri-ciri ikon yang mendefinisikan Jepang, dari boneka Daruma hingga ikan Koi!</p>',
        'medals_zh' => '<p>奖牌的正面跟背面，你都可以看到一名站定位的武士，代表决斗准备开始了。</p><p>武士的身后，有两把武士刀。武士刀象征着武士的灵魂，也代表着他的阶级，可说是这面奖牌的灵魂所在。武士的帅气、毅力和信念，都在这里了！</p><p>奖牌的背面，还有许多日本的经典元素，像是不倒翁，还有飘扬的锦鲤旗。当你拿到这个奖牌，你得到的不止是最强武士的封号，还有这充满日本风味的专属纪念品！</p>',
        'header' => 'samurai.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Christmas Virtual Run 2018',
        'title_ms' => 'Larian Virtual Krismas 2018',
        'title_zh' => '圣诞节线上跑2018',
        'date_from' => '2018-04-12',
        'date_to' => '2018-04-14',
        'dead_from' => '2018-04-06',
        'dead_to' => '2018-04-10',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>On the first day of Christmas, my true love gave to me… the opportunity to join Christmas Virtual Run 2018!</p><p>Start off this festive season by being active and spreading the joys of a healthier lifestyle! Since it’s the season of giving, gift yourself and your loved ones, the opportunity to be healthy!</p><p>We've planned it so that your finisher's medal will arrive just in time to hopefully be the first Christmas present you'll receive for the season! It'll also come in handy as a beautiful ornament to hang on your Christmas tree!</p><p>So, gather all your family and friends, and have a joyous time running towards a better tomorrow - and remember, the more, the merrier!</p>",
        'about_ms' => '<p>Mulakan musim perayaan ini dengan aktif dan menyebarkan kegembiraan gaya hidup yang lebih sihat! Pada musim pemberian ini, hadiahkanlah kepada diri sendiri dan orang yang anda sayangi, peluang untuk menjadi sihat! </p><p>Kami telah merancang supaya pingat penamat anda akan tiba tepat pada masanya. Semoga ia menjadi hadiah Hari Krismas yang pertama yang akan anda terima untuk musim ini! Ia juga berguna sebagai hiasan yang indah untuk digantung pada pokok Krismas anda!</p><p>Oleh itu, kumpulkan semua keluarga dan kawan-kawan anda pada musim cuti ini dan berseronok bersama - dan ingatlah, lebih ramai, lebih meriah!</p>',
        'about_zh' => '<p>圣诞节的那一天，我遇见了我的真爱，而他 / 她邀请我……一起去参加圣诞节线上跑2018！</p><p>12月的圣诞季，要怎么过呢？不如就动动身子，一起享受健康生活的乐趣吧！既然「给予」是圣诞节最重要的精神，那么今年，就送给自己和所爱之人，一个变健康的机会吧！</p><p>我们精心策画，就是为了让你的完赛奖牌，成为你在圣诞季收到的第一份礼物！这面奖牌还可以当作圣诞树上的装饰，实用又好看！</p><p>赶快拉着你的亲朋好友，一起跑向更美好的未来吧——噢噢，别忘了，人越多，就越好玩！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>This medal takes the shape of a snowglobe with an igloo to substitute the bottom. A waving reindeer is at the door to greet you too!</p><p>Inside the sphere, Santa is holding up a present by a big Christmas tree - this symbolises this medal as a reward for you in exchange for the effort you have put in to complete this run!</p><p>The coolest thing about this medal? You can detach it from it\'s lanyard to use it as a decoration piece around your home for the festive season! We\'ve made sure to leave an ample amount of time for you to receive your medal, so that it\'ll arrive just like an early Christmas present from us!</p>',
        'medals_ms' => '<p>Pingat ini berbentuk Glob Salji dengan igloo untuk menggantikan bahagian bawah. Terdapat juga seekor rusa melambai di pintu seakan menyambut anda!</p><p>Di dalam sfera, terdapat Santa memegang hadiah di sebelah pokok Krismas yang besar - pingat ini hadiah untuk anda sebagai pertukaran untuk usaha yang telah anda berikan untuk menyempurnakan larian ini!</p><p>Apa yang menarik sekali mengenai pingat ini ialah anda boleh mengasingkannya dari lanyard untuk digunakan sebagai hiasan di rumah anda sewaktu musim perayaan! Kami telah merancang masa bagi memastikan anda menerima pingat seperti hadiah Krismas awal dari kami!</p>',
        'medals_zh' => '<p>这面奖牌以水晶球为主体，并且用雪地小屋作为基座。你看你看，有只麋鹿在小屋的门边，正向着你招手呢！</p><p>水晶球里，有棵好大的圣诞树，树下的圣诞老人，手里抱着一份礼物。这是什么意思呢？其实啊，这面奖牌就是给你的礼物，作为你努力完成这个比赛的回报喔！</p><p>最酷的是，你可以把奖牌的挂绳拆掉，然后拿来装饰你的家里！另外，我们精心计算运送的时间，确保你能够准时收到你的奖牌，它，将成为我们送给你的圣诞礼物！</p>',
        'header' => 'christmas.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Retro Virtual Run',
        'title_ms' => 'Larian Virtual Retro 2018',
        'title_zh' => '复古风线上跑',
        'date_from' => '2018-06-22',
        'date_to' => '2018-06-30',
        'dead_from' => '2018-06-18',
        'dead_to' => '2018-06-20',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>Go back to simpler times with the Retro Virtual Run 2018 - where all you needed was some good music and the great outdoors! Prep your playlist with some retro tunes, pop on your headphones and go out for a run!</p><p>Let's take this time to reminisce the past and truly appreciate where we came from too!</p><p>Fun fact: Did you know that to retro run is to run backwards? Why not go all out and try it out! But, please don't get hurt while doing so!</p>",
        'about_ms' => '<p>Kembali ke masa yang lebih mudah dengan Larian Virtual Retro 2018 - di mana semua yang anda perlukan adalah muzik dan aktivit luaran yang bagus! Sediakan senarai main anda dengan lagu lagu retro, pop pada fon kepala anda dan keluar untuk berlari!</p><p>Ayuh kita ambil masa ini untuk mengenang masa lalu dan benar-benar menghargai asal usul kita juga!</p><p>Fakta sambilan: Adakah anda tahu bahawa berlari retro adalah dengan berjalan ke belakang? Mengapa tidak pergi keluar dan mencubanya! Tetapi, jangan abaikan keselamatan anda!</p>',
        'about_zh' => '<p>就让我们跟着复古风线上跑 2018的脚步，回到那段简单美好时代吧！那时候的我们，只要来一点音乐，再到户外走一走，就很满足了～今天就试试看，准备一些复古的歌曲，戴上耳机，就出门跑个步吧！</p><p>这是个我们能够好好回首过往，并且因此心存感激的时刻！</p><p>你知道吗：在英文里面，所谓怀旧复古的跑法，就是真的往后倒退跑！你也可以试试看～不过倒退跑的时候，要小心别受伤了喔！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>Modeled after the shape of an antique pocket watch, this medal design best represents the beauty and timelessness of the past. The old gold colour of the medal also potrays the colour\'s popularity back in the olden days.</p><p>On the front, the intricate design of the inner gears can be seen. This symbolises the different \'parts\' in our life which contributes to our successes both in and out of running.</p><The back of the medal, with it\'s funky leaf pattern, is a nod to the 60s and 70s where loving and protecting nature was all the rage!</p>',
        'medals_ms' => '<p>Diilhamkan dari bentuk jam tangan poket antik, reka bentuk pingat ini lebih baik melambangkan kecantikan dan waktu lapang masa lalu. Warna emas pada pingat juga melambangkan populariti dan kegemilangan warna ini pada zaman dahulu.</p><p>Di bahagian depan, reka bentuk rumit gear dalaman dapat dilihat. Ini melambangkan pengalaman yang berbeza dalam kehidupan kita yang menyumbang kepada kejayaan kita.</p><p>Corak daun di belakang pingat, mengimbau zaman tahun 60-an dan 70-an di mana sifat penyayang dan melindungi alam sekitar amatlah dipupuk!</p>',
        'medals_zh' => '<p>以复古的怀表为造型，这面奖牌可说是过去辉煌年代的最佳象征！闪亮的金色，也正是以前非常流行的颜色呢。</p><p>奖牌的正面，你可以看见怀表内部，有着好多精细的齿轮。每个齿轮，都好像是我们人生里的不同部分，当它们一一组合起来，就能带领我们迈向成功。不论是跑步，或是其他方面的。</p><p>奖牌的背面，刻着放克风格的树叶图案，这是为了向爱护自然的70、80年代致敬！</p>',
        'header' => 'retro.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => ' Unicorn Virtual Run',
        'title_ms' => 'Larian Virtual Unicorn',
        'title_zh' => '独角兽线上跑',
        'date_from' => '2018-07-23',
        'date_to' => '2018-07-25',
        'dead_from' => '2018-07-15',
        'dead_to' => '2018-07-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'category' => '3km,5km,10km,21km',
        'price' => 50.00,
        'about_en' => "<p>Famously associated with rainbows, glitter and all things cute, the unicorn has become a universal symbol of peace and happiness! A gentle and innocent creature, its horn is even said to have magical healing powers!</p><p>Not only that, unicorns also symbolise power and strength. Hence, many people associate unicorns with striving for excellence always!</p><p>Let's all be like unicorns and achieve new running distances in our journeys to become better runners!</p>",
        'about_ms' => '<p>Terkenal terkait dengan pelangi, glitter dan semua hal lucu, unicorn telah menjadi simbol perdamaian dan kebahagiaan universal! Makhluk lembut dan polos, tanduknya bahkan dikatakan memiliki kekuatan penyembuhan magis!</p><p>Tidak hanya itu, unicorn juga melambangkan daya dan kekuatan. Oleh karena itu, banyak orang mengasosiasikan unicorn dengan selalu berusaha untuk selalu unggul!</p><p>Mari kita semua menjadi seperti unicorn dan mencapai jarak lari baru dalam perjalanan kita untuk menjadi pelari yang lebih baik!</p>',
        'about_zh' => '<p>说到独角兽，你会想到什么呢？噢，你说鲜艳的彩虹、亮晶晶的光芒，和各式各样可爱的东西吗？没错，不论在世界的哪个角落，独角兽都可说是和平和快乐的最佳代表！它温顺又天真无邪，而且你知道吗，据说独角兽头上的角，还有着神奇的治愈力量喔！</p><p>不只如此，独角兽还可以代表力量，看到它，就像是看到每天都力求精进的自己！</p><p>让我们一起，跟着独角兽的脚步，向前迈进，在跑步的过程中，成为更好的自己吧！</p>',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p>",
        'awards_ms' => '<p>Dapatkan kesempatan untuk menang hadiah keren ini saat anda mendaftar untuk lomba ini.</p>',
        'awards_zh' => '<p>注册这场比赛，你将有机会赢得这个很酷的奖品</p>',
        'medals_en' => '<p>This medal takes the shape of the top of a unicorn’s head with its horn coloured just like a rainbow! Two unicorns can also be seen happily hopping around a rainbow – showing off their happy and carefree personalities.</p><p>On the back, the slogan ‘Chasing the Unicorn’ is placed in between two unicorns to remind us to constantly do our best and strive for excellence in whatever we do!</p><p>The medal piece also doubles as a comb when you take it off its lanyard - cute and functional!</p>',
        'medals_ms' => '<p>Medali ini mengambil bentuk bagian atas kepala unicorn dengan tanduknya yang berwarna seperti pelangi! Dua unicorn juga dapat dilihat dengan gembira melompat di sekitar pelangi - memamerkan kepribadian mereka yang bahagia dan tanpa beban.</p><p>Di belakang, slogan \'Chasing the Unicorn\' ditempatkan di antara dua unicorn untuk mengingatkan kita untuk terus melakukan yang terbaik dan berusaha untuk mencapai keunggulan dalam apa pun yang kita lakukan!</p><p>Potongan medali juga berfungsi sebagai sisir saat anda melepaskannya dari lanyard - lucu dan fungsional!</p>',
        'medals_zh' => '<p你发现了吗？这面奖牌是以独角兽的头部为主体，上面的角，还是七彩的颜色！你还可以看到两只独角兽，正开心地绕着彩虹跳跃着，哇，好想跟它们一样，过的这么无忧无虑啊～</p><p>奖牌的背面，在两只可爱的独角兽中间，刻着「跟上独角兽的脚步」的标语，提醒着我们，不论做什么事，都要一直全力以赴，追求更好的自己！ （握拳</p><p>这面奖牌，还有个超酷的隐藏功能——把上面的挂绳拿掉的话，就可以当成梳子用啰，是不是可爱又实用呢～</p>',
        'header' => 'retro.jpg',
      ]);

    }
}
