<?php

use Illuminate\Database\Seeder;

class RacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*DB::table('races')->insert([
            'title' => '21Day Challenge Sep 2018',
            'date_from' => '2018-08-17 00:00 am',
            'date_to' => '2018-08-21 00:00 am',
            'dead_from' => '2018-08-09 00:00 am',
            'dead_to' => '2018-08-16 00:00:00 am',
            'price' => 122.00,
            'about' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
            'awards' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
            'header' => 'WEB BANNER  1900x1000_1534488318.jpg',
      ]);*/

      DB::table('races')->insert([
        'title_en' => 'Merdeka Virtual Run',
        'title_ms' => 'Larian Virtual Merdeka',
        'title_zh' => '国庆日跑',
        'date_from' => '2018-09-23',
        'date_to' => '2018-09-25',
        'dead_from' => '2018-09-14',
        'dead_to' => '2018-09-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 0,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'about_ms' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'about_zh' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span></p>",
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_zh' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'medals_en' => "<p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'medals_ms' => "<p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'medals_zh' => "<p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'header' => 'merdeka-run.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Bangi Wonderland Non-Competitive Ride 130km',
        'title_ms' => 'Bangi Wonderland Bukan Kompetitif 130km',
        'title_zh' => 'Bangi Wonderland 非竞赛 130公里',
        'date_from' => '2018-08-23',
        'date_to' => '2018-08-25',
        'dead_from' => '2018-08-18',
        'dead_to' => '2018-08-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Charity Red Socks Run Banner.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Family Run Ride Walk',
        'title_ms' => 'Larian Keluarga',
        'title_zh' => '家庭开心跑骑走',
        'date_from' => '2018-06-28',
        'date_to' => '2018-06-30',
        'dead_from' => '2018-06-20',
        'dead_to' => '2018-06-27',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Charity Family Fun Ride & Walk Poster.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'We Love Klang Run 2018',
        'title_ms' => 'Larian Kita Sayangi Klang 2018',
        'title_zh' => '我们爱巴生跑 2018',
        'date_from' => '2018-09-23',
        'date_to' => '2018-09-25',
        'dead_from' => '2018-09-15',
        'dead_to' => '2018-09-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'WLKR 2018 Howei Thumbnail_0.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'PPGS IPOH 5KM',
        'title_ms' => 'PPGS IPOH 5KM',
        'title_zh' => 'PPGS 怡保 5公里',
        'date_from' => '2018-11-07',
        'date_to' => '2018-11-09',
        'dead_from' => '2018-10-31',
        'dead_to' => '2018-11-06',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'hos-thumb.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Autism Charity Run 2018',
        'title_ms' => 'Larian Autisme 2018',
        'title_zh' => '自闭爱心跑 2018',
        'date_from' => '2018-12-15',
        'date_to' => '2018-12-17',
        'dead_from' => '2018-12-12',
        'dead_to' => '2018-12-14',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Autism Chairty Ruhn Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Charity Run',
        'title_ms' => 'Larian Amal 2018',
        'title_zh' => '爱心跑 2018',
        'date_from' => '2019-03-12',
        'date_to' => '2019-03-06',
        'dead_from' => '2019-02-26',
        'dead_to' => '2019-03-03',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'PROJEK KASIH Charity Run 4k x 4k This-page-001.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Lemang @Bentong fun run',
        'title_ms' => 'Larian Lemang Bentong',
        'title_zh' => '文东Lemang跑',
        'date_from' => '2019-01-23',
        'date_to' => '2019-01-25',
        'dead_from' => '2019-01-16',
        'dead_to' => '2019-01-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'lemang_thumb.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Peace road charity run penang',
        'title_ms' => 'Larian Amal Penang',
        'title_zh' => '槟城和平路爱心跑',
        'date_from' => '2019-02-02',
        'date_to' => '2019-02-04',
        'dead_from' => '2019-01-25',
        'dead_to' => '2019-02-01',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Peace Road Charity Run Penang 2018 Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Star Track Charity',
        'title_ms' => 'Amal Star Track',
        'title_zh' => 'Star Track爱心',
        'date_from' => '2019-02-15',
        'date_to' => '2019-02-17',
        'dead_from' => '2019-02-07',
        'dead_to' => '2019-02-14',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'StartrackCRFRThumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Ultimate trails of penang',
        'title_ms' => 'Laluan Penang',
        'title_zh' => '槟城终极步道',
        'date_from' => '2018-04-12',
        'date_to' => '2018-04-14',
        'dead_from' => '2018-04-06',
        'dead_to' => '2018-04-10',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Ultimate Trails Of Penang 2018 Thumbnail.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'Bangi Wonderland 130km',
        'title_ms' => 'Bangi Wonderland 130km',
        'title_zh' => 'Bangi Wonderland 130公里',
        'date_from' => '2018-06-22',
        'date_to' => '2018-06-30',
        'dead_from' => '2018-06-18',
        'dead_to' => '2018-06-20',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'Bangi Wonderland Non-Competitive 130km Thumbnail_0.jpg',
      ]);

      DB::table('races')->insert([
        'title_en' => 'The Last Tanjung Aru',
        'title_ms' => 'Tanjung Aru Terakhir',
        'title_zh' => '最后的丹戎阿如',
        'date_from' => '2018-07-23',
        'date_to' => '2018-07-25',
        'dead_from' => '2018-07-15',
        'dead_to' => '2018-07-22',
        'time_from' => '00:00 am',
        'time_to' => '23:59 pm',
        'deadtime_from' => '00:00 am',
        'deadtime_to' => '23:59 pm',
        'price' => 50.00,
        'about_en' => "<p>Welcome to the September 21 Day Challenge – Virgo!</p><p><br></p><p>Virgos are the perfect blend of perfectionism and pragmatism. Although they set sky-high expectations for themselves, they remain grounded by working towards achievable, short-term targets. </p><p><br></p><p>This 21 Day Challenge, don’t be afra <span style=\"color: rgb(205, 19, 19);\">Read More...</span></p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1d-gif-uab10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></h2><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-1D-jpg-9fs10082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-2D-jpg-su910082018-105503\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-3D-jpg-k2b08082018-145930\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-4A-jpg-pzf09082018-142436\" alt=\"21Day Challenge Sep 2018 medal\"></p><p><br></p><p><span class=\"ql-cursor\">﻿</span>Medals</p><p>Virgo’s element is the Earth. Our medal reflects this, showing her relaxing peacefully among the beautiful elements of nature. As we run to improve ourselves, let's remember not to get too caught up in the competition. Stop &amp; smell the flowers along the way! (:  </p>",
        'about_ms' => 'about dalam bahasa melayu',
        'about_zh' => '关于',
        'awards_en' => "<p>Get a chance to win these cool prizes when you register</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/icrossedline-meitu-13-jpg-3az21062017-160444\" width=\"100%\">Inspirational Awards x 3</h2><p>Metallic Double Layer Medal Hanger </p><p>(worth S$59.90)</p><p>Material: Metal</p><p>Nett weight: 480g</p><p>Size: 48cm x 17.4cm</p><h2><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/gift-box-01-jpg-ffi14062017-174812\" width=\"100%\">Lucky Draw Winners x 50</h2><p>Runner's Gift Set (worth S$29.90)</p><p>2018 Serial Challenge Award</p><p>There are 3 types of special awards for our 2018 21Day challenges. The following awards are given to all who satisfy the respective criteria. Limited to one award per person. Grand Slam/Super Runner medal photo is for reference only, actual product might slightly differ.</p><p><img src=\"https://virtual-race-submissions.s3-ap-southeast-1.amazonaws.com/images/MEDAL-BANNER-GRAND-SLAM-AWARD-1-jpg-q2r13022018-91136\">Grand Slam Award</p><p>Complete 12 challenges with min of 100km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Grand Slam Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Super Runner Award</p><p>Complete 9 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Special Super Runner Finisher’s Medal&nbsp;</p><p>2.&nbsp;Hall of Fame&nbsp;</p><p>3.&nbsp;Invitation to 2018 year end celebration party (in Singapore)</p><p>Power Runner Award</p><p>Complete 6 challenges with min of 20km for each challenge</p><p>Awards</p><p>1.&nbsp;Hall of Fame</p>",
        'awards_ms' => 'awards dalam bahasa melayu',
        'awards_zh' => '奖项',
        'medals_en' => 'Medals in english',
        'medals_ms' => 'Medals in bahasa melayu',
        'medals_zh' => 'Medals in chinese',
        'header' => 'The Last Tanjung Aru Beach Run 2018 Thumbnail.jpg',
      ]);
    }
}
